version: '3.2'

services: 
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.dockerfile
    volumes: 
      - .:/var/www
    links:  
      - mysql
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
      - "443:443"
    links:  
      - php-fpm
  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
   db-data: